// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9lqoESiSRfEbPEyqiyYO-Hpi8njvTpwc',
    appId: '1:142732379073:web:4f126770419a11d58a6540',
    messagingSenderId: '142732379073',
    projectId: 'myshopapp-84e8f',
    authDomain: 'myshopapp-84e8f.firebaseapp.com',
    storageBucket: 'myshopapp-84e8f.firebasestorage.app',
    measurementId: 'G-5JWRT8N6Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2L5KU2GOWbSggjOqQfoXqXpP7VmAK8x0',
    appId: '1:142732379073:android:cee59e617eb5351d8a6540',
    messagingSenderId: '142732379073',
    projectId: 'myshopapp-84e8f',
    storageBucket: 'myshopapp-84e8f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3rEAlw2GqFNUmBm78cF6doTFLjPDaOVE',
    appId: '1:142732379073:ios:71b771c0f56b578b8a6540',
    messagingSenderId: '142732379073',
    projectId: 'myshopapp-84e8f',
    storageBucket: 'myshopapp-84e8f.firebasestorage.app',
    iosBundleId: 'com.example.justcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3rEAlw2GqFNUmBm78cF6doTFLjPDaOVE',
    appId: '1:142732379073:ios:71b771c0f56b578b8a6540',
    messagingSenderId: '142732379073',
    projectId: 'myshopapp-84e8f',
    storageBucket: 'myshopapp-84e8f.firebasestorage.app',
    iosBundleId: 'com.example.justcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9lqoESiSRfEbPEyqiyYO-Hpi8njvTpwc',
    appId: '1:142732379073:web:fcfe78a0c14bbc0d8a6540',
    messagingSenderId: '142732379073',
    projectId: 'myshopapp-84e8f',
    authDomain: 'myshopapp-84e8f.firebaseapp.com',
    storageBucket: 'myshopapp-84e8f.firebasestorage.app',
    measurementId: 'G-Z68JBS4F3X',
  );
}
