import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';

import 'firebase_options.dart'; // auto-generated by flutterfire configure
import 'sign_in_page.dart';
import 'sign_up_page.dart';
import 'home_content.dart';
import 'cart_state.dart'; // 🔁 Import for syncCartFromFirestore

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyShopApp());
}

class MyShopApp extends StatefulWidget {
  const MyShopApp({super.key});

  @override
  State<MyShopApp> createState() => _MyShopAppState();
}

class _MyShopAppState extends State<MyShopApp> {
  @override
  void initState() {
    super.initState();

    // ✅ Sync cart when user logs in
    FirebaseAuth.instance.authStateChanges().listen((user) {
      if (user != null) {
        syncCartFromFirestore(); // 🔄 Load saved cart
      }
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      debugShowCheckedModeBanner: false,
      title: 'Shopping App',
      initialRoute: '/',
      routes: {
        '/': (context) => const SignInPage(),
        '/signup': (context) => const SignUpPage(),
        '/home': (context) => HomeContent(),
      },
    );
  }
}
